# Generated by Django 3.2.7 on 2021-10-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('somoim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moim',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_moim', to=settings.AUTH_USER_MODEL, verbose_name='리더'),
        ),
        migrations.AddField(
            model_name='moim',
            name='members',
            field=models.ManyToManyField(related_name='member_moim', to=settings.AUTH_USER_MODEL, verbose_name='멤버'),
        ),
        migrations.AddField(
            model_name='article',
            name='moim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='somoim.moim', verbose_name='모임'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
