# Generated by Django 3.2.7 on 2021-10-13 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('somoim', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moim',
            name='members',
            field=models.ManyToManyField(null=True, related_name='member_moim', to=settings.AUTH_USER_MODEL, verbose_name='멤버'),
        ),
    ]
