# Generated by Django 3.2.7 on 2021-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somoim', '0004_auto_20211013_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('location', models.CharField(max_length=64, verbose_name='장소')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
        migrations.RemoveField(
            model_name='moim',
            name='city',
        ),
        migrations.RemoveField(
            model_name='moim',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='moim',
            name='province',
        ),
    ]
