# Generated by Django 3.2.7 on 2021-10-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somoim', '0005_auto_20211014_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='moim',
        ),
        migrations.AddField(
            model_name='schedule',
            name='moim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='somoim.moim', verbose_name='모임'),
        ),
    ]
