# Generated by Django 3.2.7 on 2021-10-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('somoim', '0006_auto_20211014_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='moim',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_moims', to=settings.AUTH_USER_MODEL, verbose_name='리더'),
        ),
        migrations.AlterField(
            model_name='moim',
            name='members',
            field=models.ManyToManyField(null=True, related_name='member_moims', to=settings.AUTH_USER_MODEL, verbose_name='멤버'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='moim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somoim.moim', verbose_name='모임'),
        ),
    ]
