# Generated by Django 3.2.7 on 2021-10-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somoim', '0007_auto_20211014_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='moim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='somoim.moim', verbose_name='모임'),
        ),
    ]
