# Generated by Django 3.2.7 on 2021-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somoim', '0008_alter_schedule_moim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(verbose_name='시간'),
        ),
    ]
