# Generated by Django 3.2.7 on 2021-10-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(null=True, verbose_name='사진'),
        ),
    ]
